---
layout: cv
---
# Amber Robbins

## Software Engineer

### Contact

ajrobbins04@gmail.com   
(702) 308-6129   
Henderson, NV

[LinkedIn Profile](https://www.linkedin.com/in/amber-robbins-47a261189/)

### Summary
Motivated computer science major with a burgeoning interest in data science. Proven team leader and collaborative team member known for strong interpersonal skills and meticulous attention to detail. Experienced in software design and web development, leading successful group projects and excelling in technical problem-solving. Seeking opportunities in a dynamic work environment to grow and contribute to a forward-thinking team, dedicated to continuous learning and excellence.

### Technical Skills

* **Programming Languages:** Python, C++, JavaScript, HTML/CSS, SQL, Erlang (basic)
* **Web Development:** Node.js, PHP
* **Advanced CSS Concepts:** Flexbox, Grid, Animations, Responsive Design
* **Software Design:** Object-Oriented Design, Design Patterns
* **Data Science Tools:** Pandas, NumPy, Scikit-Learn, Plotly Express
* **Databases:** MySQL, MongoDB
* **Version Control:** Git, GitHub
* **Development Tools:** VS Code, Xcode, Jupyter Notebook
* **Operating Systems:** macOS, Linux (basic)

### Soft Skills

* **Leadership:** Experience leading teams of 2-5 members in group projects
* **Collaboration:** Strong interpersonal skills, effective team player
* **Communication:** Clear and concise communicator, both written and verbal
* **Problem-Solving:** Analytical thinker, adept at finding creative solutions
* **Detail-Oriented:** Meticulous attention to detail, committed to quality work
* **Adaptability:** Quick learner, capable of picking up new technical skills
* **Self-Motivated:** Driven to succeed, dedicated to continuous learning and growth

### Experience

* **Software Design:** Designed and implemented software solutions using object-oriented principles and design patterns in various projects.
* **Full Stack Web Development:** Developed full-stack web applications using Node.js and PHP, focusing on both front-end and back-end functionalities.
* **Object-Oriented Programming:** Applied OOP concepts in multiple programming languages, including Python and C++, to build scalable and maintainable code.
* **Data Science:** Utilized data science tools and libraries, such as Pandas and NumPy, to analyze and visualize data in various projects.
* **Functional Programming:** Gained experience with functional programming paradigms and techniques through coursework and projects.

### Education

**Brigham Young University - Idaho**, Rexburg, ID  
* **Bachelor of Science in Computer Science**  
* September 2020 - December 2025 (Expected Graduation Date)   
* GPA: 3.9

**Basic High School**, Henderson, NV  
* **High School Diploma with Honors**  
* August 2010 - June 2014  
* Valedictorian

<!-- ### Footer

Last updated: May 2013 -->